# Generated by Django 5.1.7 on 2025-04-10 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailactivation',
            options={'verbose_name': 'Email Activation', 'verbose_name_plural': 'Email Activations'},
        ),
    ]
