# Generated by Django 5.1.7 on 2025-03-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pdfdocument_user_text_user_video_user_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarynotes',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
