# Generated by Django 5.1.7 on 2025-03-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_summarynotes_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarynotes',
            name='content_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
